name: "scrollbar_ultima"
description: "ScrollBarUltima is a powerful Flutter package that allows you to create highly customizable scrollbars!"
version: 1.0.4
homepage: "https://github.com/C0ntrolDev/scrollbar_ultima"
repository: "https://github.com/C0ntrolDev/scrollbar_ultima"

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0